from .shallownet import ShallowNet
from .lenet import LeNet
from .minivggnet import MiniVGGNet
from .fcheadnet import FCHeadNet
from .alexnet import AlexNet
from .minigooglenet import MiniGoogLeNet
from .deepergooglenet import DeeperGoogLeNet
from .googlenet2 import GoogLeNet2
from .resnet import ResNet
from .emotionVGGNet import EmotionVGGNet